//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtGalleryApplication.DBEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArtGalleryEntities : DbContext
    {


        public ArtGalleryEntities()
            : base("name=ArtGalleryEntities")
        {
        }

       
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Artist> Artist { get; set; }
        public virtual DbSet<Exhibition> Exhibition { get; set; }
        public virtual DbSet<Exposition> Exposition { get; set; }
        public virtual DbSet<Genre> Genre { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<Picture> Picture { get; set; }
        public virtual DbSet<PieceOfArt> PieceOfArt { get; set; }
        public virtual DbSet<PieceOfArtHasGenre> PieceOfArtHasGenre { get; set; }
        public virtual DbSet<PieceOfArtHasMaterial> PieceOfArtHasMaterial { get; set; }
        public virtual DbSet<PieceOfArtHasStile> PieceOfArtHasStile { get; set; }
        public virtual DbSet<PieceOfArtHasTechnique> PieceOfArtHasTechnique { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Stile> Stile { get; set; }
        public virtual DbSet<Technique> Technique { get; set; }
        public virtual DbSet<User1> User1 { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
    }
}
