//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtGalleryApplication.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exposition
    {
        public int ID { get; set; }
        public int Exhibition { get; set; }
        public int PieceOfArt { get; set; }
    
        public virtual Exhibition Exhibition1 { get; set; }
        public virtual PieceOfArt PieceOfArt1 { get; set; }
    }
}
